name: cached_chewie
description: Fork of official chewie with cached_video_player.
version: 1.1.0
homepage: https://github.com/vikram25897/chewie_cached


environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

  flutter_cached_video_player: ^2.0.5
  provider: ^6.0.1
  wakelock_plus: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
